name: "joao-tattoo-frontend"

services:
  app:
    build:
      context: ../
      dockerfile: docker/dev.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../src:/usr/app/src
      - ../.nuxt:/usr/app/.nuxt
      - ../server:/usr/app/server
      - ../config:/usr/app/config
